### ISSUE TITLE
Proto file with imports causes empty decoding of imported messages

### ISSUE THREAD

**Issue by Matus-p** [Kong/kong-plugin-grpc-gateway#20] opened 2021-03-30 08:21 UTC
It seems that lua-protobuf library has a bug that causes that messages from imported proto files are not decoded/encoded.
see here: https://github.com/starwing/lua-protobuf/issues/138

as an example, it causes that the SayHello grpc rpc will always receive an empty timestamp.
```
syntax = "proto3";
import "google/protobuf/timestamp.proto";
package helloworld;

service Greeter {
  rpc SayHello (HelloRequest) returns (HelloReply) {
    option (google.api.http) = {
      post: "/greeter/sayhello"
      body: "*"
    };
  }
}

message HelloRequest {
  string name = 1;
  google.protobuf.Timestamp timestamp = 2;
}

message HelloReply {
  string message = 1;
}
```
as a workaround it might help to call p:loadfile before p:parsefile here: https://github.com/Kong/kong-plugin-grpc-gateway/blob/master/kong/plugins/grpc-gateway/deco.lua#L96-L134

**Comment by fffonion** [comment] 2021-03-31 12:55
Looks like a duplicate of #15

**Comment by fffonion** [comment] 2021-06-01 11:35
Closing for duplication, please keep updated in the linked issue.

**Closed by fffonion** 2021-06-01 11:35 UTC
