### ISSUE TITLE
grpc-gateway json parsing error

### ISSUE THREAD

**Issue by liuzhenbin96** [Kong/kong-plugin-grpc-gateway#9] opened 2020-09-25 05:56 UTC
Json parsing error occurs when more than 16KB of data is returned

**Comment by fffonion** [comment] 2020-09-25 08:31
Hi @liuzhenbin96 , there might be an hard limit somewhere. Can you shared an example of proto file and the kong error log when it occurs?

**Comment by liuzhenbin96** [comment] 2020-09-27 01:53
The proto file is shown below and the field information needs to be hidden because it involves the work content
`
syntax = "proto3";
rpc QueryObjectList(QueryObjectListRequest) returns (QueryObjectListResponse) {
    option (google.api.http) = {
      post: "object/queryObjectList"
      body: "*"
    };
  }

message QueryObjectListRequest {
}

message QueryObjectListResponse {
  int64 returnCode = 1;
  string returnMsg = 2;
  string returnUserMsg = 3;
  ObjectList data = 4;
}

message ObjectList {
  repeated Object list = 1;
}

message Object {
  string field1 = 1; 
  string field2 = 2;
  string field3 = 3;
  string field4 = 4;
  int32 field5 = 5;
  int32 field6 = 6;
  int32 field7 = 7;
  int32 field8 = 8;
  int32 field9 = 9;
  int32 field10 = 10;
  double field11 = 11;
  int32 field12 = 12;
  int32 field13 = 13;
  int32 field14 = 14;
}
`
Using postman's test results:
normal：
![image](https://user-images.githubusercontent.com/20379106/94353680-786e5580-00a6-11eb-857f-6d5359082ec1.png)
abnormal：
![image](https://user-images.githubusercontent.com/20379106/94353689-976ce780-00a6-11eb-9c0c-f055eadec15d.png)

**Comment by gszr** [comment] 2020-09-30 17:12
@liuzhenbin96 Could you share the relevant portions of Kong logs - do you see any grpc-gateway errors in there?

**Comment by liuzhenbin96** [comment] 2020-10-09 02:06
> @liuzhenbin96 Could you share the relevant portions of Kong logs - do you see any grpc-gateway errors in there?

[kong.grpc-gateway报文16k日志截取内容.docx](https://github.com/Kong/kong-plugin-grpc-gateway/files/5352135/kong.grpc-gateway.16k.docx)

**Comment by fffonion** [comment] 2020-10-09 06:25
@liuzhenbin96 the behaviour from the postman output looks like the plugin is not able to decode protobuf response, so let the response body unmodified, then the client receives the raw protobuf message instead of a json.
could you try [this branch](https://github.com/Kong/kong-plugin-grpc-gateway/tree/log) where some basic logging is added?
also please share the `grpc-status` and `grpc-message` in response header if there's any.

**Comment by liuzhenbin96** [comment] 2020-10-09 08:23
> @liuzhenbin96 the behaviour from the postman output looks like the plugin is not able to decode protobuf response, so let the response body unmodified, then the client receives the raw protobuf message instead of a json.
> could you try [this branch](https://github.com/Kong/kong-plugin-grpc-gateway/tree/log) where some basic logging is added?
> also please share the `grpc-status` and `grpc-message` in response header if there's any.

The log can refer to my last reply

**Comment by fffonion** [comment] 2020-10-09 08:31
@liuzhenbin96 That log is not helpful to be honest, it's not possible to decipher protobuf in plaintext, and we don't know which variable you are logging.

**Comment by liuzhenbin96** [comment] 2020-10-10 02:57
> @liuzhenbin96 That log is not helpful to be honest, it's not possible to decipher protobuf in plaintext, and we don't know which variable you are logging.

正确返回打印日志：
2020/10/10 02:34:09 [debug] 23#0: *625 [kong] deco.lua:157 [grpc-gateway] rewrite to grpc path: /warebasic.StationService/QueryStationList
2020/10/10 02:34:09 [debug] 23#0: *625 [kong] deco.lua:196 [grpc-gateway] unframed body size is 16
10.170.120.76 - - [10/Oct/2020:02:34:09 +0000] "POST /wes/warebasic/station/queryStationList HTTP/1.1" 200 122 "-" "curl/7.29.0"
2020/10/10 02:34:09 [info] 23#0: *625 client 10.170.120.76 closed keepalive connection

错误返回打印日志：
2020/10/10 02:34:50 [debug] 23#0: *947 [kong] deco.lua:157 [grpc-gateway] rewrite to grpc path: /warebasic.StationService/QueryStationList
2020/10/10 02:34:50 [debug] 23#0: *947 [kong] deco.lua:196 [grpc-gateway] unframed body size is 4641
2020/10/10 02:34:50 [debug] 23#0: *947 [kong] deco.lua:196 [grpc-gateway] unframed body size is 4641
10.170.120.76 - - [10/Oct/2020:02:34:50 +0000] "POST /wes/warebasic/station/queryStationList HTTP/1.1" 200 21117 "-" "curl/7.29.0"
2020/10/10 02:34:50 [info] 23#0: *947 client 10.170.120.76 closed keepalive connection

**Comment by fffonion** [comment] 2020-10-12 07:53
Thanks @liuzhenbin96. This looks weird, from log everything looks normal. Let me try to reproduce.

**Comment by aaronggi** [comment] 2020-10-29 21:31
Also ran into this issue, it seemed like >4kb body size the responses started containing a mix of binary data and the actual expected json response. Was just curious if a fix for this was coming down the pike? 

Thank you!

**Comment by fffonion** [comment] 2020-10-30 06:44
I feel there's something wrong in the way the response is currently decoded, but I can't actually verify it since I can't reproduce it locally. @aaronggi is the backend server returning body in multiple responses?

**Comment by aaronggi** [comment] 2020-11-02 16:32
@fffonion I believe the backend server is returning a single response.

I've uploaded my repo, with the plugin being loaded manually for debugging, if that helps-- https://github.com/aaronggi/kong-project-poc

After running the docker-compose, you can reproduce the error with `curl -XGET localhost:8000/loss/123/result/event --output -`

**Comment by fffonion** [comment] 2020-11-03 05:48
@aaronggi thank you, that helps a lot, I will try to reproduce on my side.

**Comment by fffonion** [comment] 2020-11-03 16:14
@aaronggi @liuzhenbin96 I made a fix in #12, it works with the above POC. If you could try with that patch that will be helpful :)

**Comment by aaronggi** [comment] 2020-11-04 17:35
@fffonion Thanks for the quick fix! Tested it and looks like it's all set 👍

**Closed** 2020-11-05 06:53 UTC
Labels: bug
